const SAVE_KEY = "dalu-travel-log-save-v3";
const ROLE_LABELS = { hero: "主線英雄", hermit: "隱士", wanderer: "大陸旅人" };
const NPC_HEROES = ["米拉・風泉", "伊瑟・鐘守", "洛塔・灰帆"];
const LOCATIONS = {
  "wind-spring": { name: "風泉村", type: "聚落", settlement: "wind-spring", faction: "wind-spring-council", event: "bell", copy: "旅店、雜貨店、村政廳。地方狀態會隨世界日變化。" },
  "mist-harbor": { name: "霧港村", type: "聚落", settlement: "mist-harbor", faction: "salt-road-guild", event: "harbor", copy: "鹽路商會交換情報，晚到的船總有一個不願說出口的理由。" },
  "bell-hill": { name: "北坡鐘丘", type: "野外", settlement: "wind-spring", faction: "bell-temple", event: "bell", copy: "古老鐘丘，午夜後才會留下真正的腳印。" },
  "salt-marsh": { name: "鹽潮荒野", type: "野外", settlement: "mist-harbor", faction: "salt-road-guild", event: "marsh", copy: "退潮後露出的白色鹽脊，拾荒者說荒野正在呼吸。" },
  "sand-ruins": { name: "沉砂遺跡", type: "地城", settlement: "wind-spring", faction: "bell-temple", event: null, copy: "沉在沙下的舊城，通往鐘守 Boss 入口。" }
};
const EVENTS = {
  bell: { eyebrow: "自由事件・風泉村", title: "失落鐘聲", description: "北坡的鐘聲在午夜響起。村政廳希望你調查，神殿守門人則勸你不要靠近。", choices: [
    { id: "village", label: "接受村政廳的委託", note: "風泉村繁榮 +8／信任 +5", result: "村民把沉砂遺跡的舊地圖交給你。", effect: { prosperity: { "wind-spring": 8 }, faction: { "wind-spring-council": 5 }, unlock: "sand-ruins" } },
    { id: "temple", label: "先拜訪神殿守門人", note: "鐘守信任 +6／威脅 -3", result: "守門人標記了進入遺跡的安全路線。", effect: { threat: -3, faction: { "bell-temple": 6 }, unlock: "sand-ruins" } },
    { id: "wait", label: "在旅店等待午夜", note: "取得線索／威脅 +2", result: "你聽見鐘聲裡混著潮汐，卻錯過第一個時機。", effect: { threat: 2 } }
  ] },
  harbor: { eyebrow: "自由事件・霧港村", title: "霧港的失約船", description: "商路上的船晚了一日，鹽路商會想知道是哪一方改了航線。", choices: [
    { id: "guild", label: "替鹽路商會查航線", note: "商會信任 +7／霧港繁榮 +5", result: "商會將鹽潮荒野的安全路線交給你。", effect: { prosperity: { "mist-harbor": 5 }, faction: { "salt-road-guild": 7 } } },
    { id: "villagers", label: "先把消息告訴等船的人", note: "霧港繁榮 +7／威脅 -1", result: "霧港的夜市重新亮起燈火。", effect: { prosperity: { "mist-harbor": 7 }, threat: -1 } }
  ] },
  marsh: { eyebrow: "自由事件・鹽潮荒野", title: "鹽脊下的呼吸", description: "鹽脊裂縫傳出規律回音，和沉砂遺跡的鐘聲很像。", choices: [
    { id: "listen", label: "貼近裂縫聽完整段回音", note: "取得遺跡線索／威脅 -2", result: "你記下回音節拍，鐘守封印似乎少了一道。", effect: { threat: -2 } },
    { id: "mark", label: "在鹽脊上留下警戒標記", note: "商會信任 +3／荒野安全", result: "鹽路商會開始把你視為可靠的探路人。", effect: { faction: { "salt-road-guild": 3 } } }
  ] }
};Object.assign(EVENTS, {
  council: { eyebrow: "自由事件・地方委託", title: "井邊的缺水帳", description: "村政廳記錄的水桶數與實際對不上。居民、記帳員和商隊各有一套說法。", choices: [
    { id: "audit", label: "陪記帳員重查水路", note: "委託完成／居民信任 +3", result: "缺水帳查清了；記帳員留下下一份地方委託。", effect: { faction: { "wind-spring-council": 3 }, npc: { id: "clerk", name: "村政記帳員", trust: 3, note: "願意提供水路情報" }, commission: { id: "spring-water-followup", title: "修復上游分水閘", location: "wind-spring" } } },
    { id: "share", label: "先公開帳本請居民共同核對", note: "繁榮 +4／村政信任 +1", result: "居民一起核對帳本，村口告示板貼上了公開的分水時刻。", effect: { prosperity: { "wind-spring": 4 }, faction: { "wind-spring-council": 1 }, flag: "water-schedule-public" } }
  ] },
  shrine: { eyebrow: "自由事件・神殿", title: "沒有名字的供燈", description: "神殿側門連續三夜出現供燈，守門人希望找出留下燈的人。", choices: [
    { id: "shelter", label: "替夜歸的採藥人保密", note: "守門人信任 +3／解鎖遺跡", result: "守門人承認採藥人在守護鐘丘，並替你開啟沉砂遺跡安全路線。", effect: { faction: { "bell-temple": 3 }, npc: { id: "keeper", name: "鐘守人", trust: 3, note: "已標記安全路線" }, unlock: "sand-ruins" } },
    { id: "report", label: "依規矩向神殿報告", note: "威脅 -2／神殿巡守", result: "神殿收下燈火名冊，派人看守鐘丘。", effect: { threat: -2, flag: "shrine-watch" } }
  ] },
  guild: { eyebrow: "自由事件・工會", title: "被改過的路標", description: "鹽路商會的貨隊在荒野繞遠路，路標卻像是有人故意轉向。", choices: [
    { id: "repair", label: "和嚮導重立路標", note: "商會信任 +4／安全委託", result: "商會修復路標，並委託你護送下一批藥材。", effect: { faction: { "salt-road-guild": 4 }, commission: { id: "marsh-herbs", title: "護送鹽潮藥材", location: "salt-marsh" }, shop: { location: "mist-harbor", item: "潮鹽藥包", stock: 2 } } },
    { id: "trace", label: "追查舊車轍到退潮線", note: "威脅 -3／荒野線索", result: "車轍在退潮線消失，商會把荒野警戒提高一級。", effect: { threat: -3, flag: "marsh-trail-marked" } }
  ] },
  temporary: { eyebrow: "臨時事件・旅途", title: "雨棚下的急信", description: "一名旅人帶來急信：霧港外的倉棚漏雨，今夜前得決定先救貨還是先救人。", choices: [
    { id: "people", label: "先把滯留旅人帶進村裡", note: "霧港繁榮 +3／臨時委託", result: "旅人安頓下來；倉主留下修棚委託和一批折價補給。", effect: { prosperity: { "mist-harbor": 3 }, commission: { id: "harbor-roof", title: "修補東倉雨棚", location: "mist-harbor" }, shop: { location: "mist-harbor", item: "乾糧包", stock: 3 } } },
    { id: "cargo", label: "先救急件和藥材", note: "商會信任 +2／威脅 -1", result: "急件準時送達，商會回贈一份荒野情報。", effect: { faction: { "salt-road-guild": 2 }, threat: -1, flag: "harbor-letter-delivered" } }
  ] }
});
const EVENT_POOLS = { "wind-spring": ["bell", "council"], "mist-harbor": ["harbor", "temporary"], "bell-hill": ["shrine", "bell"], "salt-marsh": ["marsh", "guild"] };
function eventFor(location) { const pool = EVENT_POOLS[location] || []; const done = state.world.completedEvents || []; return pool.find((id) => done.indexOf(id) < 0) || null; }

const initialWorld = () => ({ day: 3, season: "春潮", threat: 18, turns: 0, npcHero: null, activeLocation: "wind-spring", settlements: { "wind-spring": 52, "mist-harbor": 38 }, factions: { "wind-spring-council": 12, "bell-temple": 0, "salt-road-guild": 0 }, unlocked: ["wind-spring", "mist-harbor", "bell-hill", "salt-marsh"], boss: false, npcs: {}, shops: {}, commissions: [], completedEvents: [], flags: [] });
const state = { screen: "journal", role: null, choices: 0, world: initialWorld() };
const q = (s) => document.querySelector(s);
const clamp = (n, a, b) => Math.max(a, Math.min(b, n));
const toast = (m) => { const n = q(".toast"); n.textContent = m; n.classList.add("show"); clearTimeout(toast.t); toast.t = setTimeout(() => n.classList.remove("show"), 2400); };
const save = (quiet) => { localStorage.setItem(SAVE_KEY, JSON.stringify({ version: 3, state })); if (!quiet) toast("旅途已儲存至本機"); };
function inject() {
  const style = document.createElement("style"); style.textContent = ".world-status-card{display:grid;gap:12px;margin-top:12px;padding:17px;border:1px solid rgba(16,44,54,.1);border-radius:21px;background:#fffdf8}.status-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.status-grid div{padding:10px;border-radius:12px;background:#edf3ef}.status-grid small,.status-grid strong{display:block}.status-grid small{font-size:10px;color:#35545d}.status-grid strong{margin-top:4px;color:#225966;font-size:19px}.map-context{display:flex;justify-content:space-between;gap:12px;margin-top:12px;padding:17px;border-radius:19px;background:#102c36;color:#fff}.map-context h3{margin:0 0 5px}.map-context p{margin:0;color:rgba(255,255,255,.72);font-size:12px;line-height:1.6}.map-context button{color:#fff;border:1px solid rgba(255,255,255,.35);background:transparent;padding:9px 13px;border-radius:12px;font-weight:700}.map-node.active,.location-row.selected{outline:2px solid #3c8290}.map-node.locked{opacity:.45}.node-harbor{left:8%;top:17%}.node-marsh{left:14%;bottom:11%}"; document.head.appendChild(style);
  const wc = q(".world-card"); if (!q(".world-status-card")) wc.insertAdjacentHTML("afterend", "<div class=\"world-status-card\"><div><p class=\"eyebrow\">地方化狀態</p><h3 id=\"region-status\">春潮海岸・風泉村</h3></div><div class=\"status-grid\"><div><small>聚落繁榮</small><strong id=\"settlement-prosperity\">52</strong></div><div><small>勢力信任</small><strong id=\"faction-reputation\">+12</strong></div><div><small>已解鎖</small><strong id=\"unlock-count\">4 / 5</strong></div></div><p id=\"world-status-copy\" class=\"status-copy\">事件結果會回寫聚落、勢力、地圖與 Boss 入口。</p></div>");
  const map = q("[data-screen=map]"); const head = map.querySelector(".page-heading").outerHTML; map.innerHTML = head + "<div class=\"map-card\"><div class=\"map-sky\"></div><div class=\"map-route route-one\"></div><div class=\"map-route route-two\"></div><button class=\"map-node node-village\" data-action=\"location\" data-location=\"wind-spring\"><span>風泉村</span><small>聚落</small></button><button class=\"map-node node-harbor\" data-action=\"location\" data-location=\"mist-harbor\"><span>霧港村</span><small>聚落</small></button><button class=\"map-node node-hill\" data-action=\"location\" data-location=\"bell-hill\"><span>北坡鐘丘</span><small>野外</small></button><button class=\"map-node node-marsh\" data-action=\"location\" data-location=\"salt-marsh\"><span>鹽潮荒野</span><small>野外</small></button><button class=\"map-node node-ruin locked\" data-action=\"location\" data-location=\"sand-ruins\"><span>沉砂遺跡</span><small>地城・Boss</small></button></div><div class=\"map-context\"><div><p class=\"eyebrow\">目前目的地</p><h3 id=\"map-context-title\">風泉村</h3><p id=\"map-context-copy\"></p></div><button data-action=\"event\">查看事件</button></div><div class=\"location-list\"></div>";
  const sheet = q(".sheet-panel"); sheet.innerHTML = "<button class=\"sheet-close\" data-action=\"close\" aria-label=\"關閉\">×</button><p class=\"eyebrow\" id=\"event-eyebrow\"></p><h2 id=\"event-title\"></h2><p id=\"event-description\"></p><div class=\"choice-list\" id=\"event-choices\"></div>";
}
function render() {
  const w = state.world; const loc = LOCATIONS[w.activeLocation]; const faction = w.factions[loc.faction] || 0;
  document.querySelectorAll("[data-role]").forEach((n) => n.classList.toggle("selected", n.dataset.role === state.role));
  q("#role-status").textContent = state.role ? ROLE_LABELS[state.role] : "尚未選擇"; q("#world-day").textContent = String(w.day).padStart(2,"0"); q("#world-threat").textContent = w.threat + "%"; q("#world-season").textContent = w.season;
  const meta = document.querySelectorAll(".hero-meta span"); if (meta[0]) meta[0].textContent = "第 " + w.day + " 日"; if (meta[1]) meta[1].textContent = loc.name + "・" + loc.type; if (meta[2]) meta[2].textContent = "回合 " + String(w.turns + 1).padStart(2,"0");
  q("#world-hero-title").textContent = state.role === "hero" ? "你已承接天命" : w.npcHero ? w.npcHero + " 承接了天命" : "天命尚未被承接"; q("#world-hero-copy").textContent = state.role === "hero" ? "主線事件會主動向你靠攏，但世界仍會在你看不見的地方繼續運轉。" : w.npcHero ? "你沒有成為英雄。新的英雄已經出現，主線將在另一條道路上前進。" : "推進世界時鐘，觀察村落、勢力與候選英雄的變化。";
  q("#region-status").textContent = "春潮海岸・" + loc.name; q("#settlement-prosperity").textContent = w.settlements[loc.settlement] || 0; q("#faction-reputation").textContent = (faction > 0 ? "+" : "") + faction; q("#unlock-count").textContent = w.unlocked.length + " / 5"; const openCount = (w.commissions || []).filter((x) => x.status === "available").length; const npcCount = Object.keys(w.npcs || {}).length; const shopCount = Object.values(w.shops || {}).reduce((n, items) => n + items.length, 0); q("#world-status-copy").textContent = w.lastResult ? w.lastResult + "　後續委託 " + openCount + " 件・相關 NPC " + npcCount + " 位・新增商品 " + shopCount + " 種" : "事件結果會回寫聚落、勢力、地圖與 Boss 入口。";
  document.querySelectorAll("[data-location]").forEach((n) => { const ok = w.unlocked.indexOf(n.dataset.location) >= 0; n.classList.toggle("locked", !ok); n.classList.toggle("active", n.dataset.location === w.activeLocation); n.setAttribute("aria-disabled", String(!ok)); });
  const availableEvent = eventFor(w.activeLocation); q("#map-context-title").textContent = loc.name; q("#map-context-copy").textContent = loc.copy; q(".map-context button").dataset.event = availableEvent || ""; q(".map-context button").disabled = !availableEvent; q(".map-context button").textContent = availableEvent ? "查看事件" : (EVENT_POOLS[w.activeLocation] ? "此地事件已完成" : (w.boss ? "鐘守已現身" : "尚未開放"));
  q(".location-list").innerHTML = Object.keys(LOCATIONS).map((id) => { const x = LOCATIONS[id]; const ok = w.unlocked.indexOf(id) >= 0; return "<button class=\"location-row " + (id === w.activeLocation ? "selected " : "") + (!ok ? "locked" : "") + "\" data-action=\"location\" data-location=\"" + id + "\"><span class=\"location-symbol\">◇</span><span><strong>" + x.name + "</strong><small>" + x.type + "・" + x.copy + "</small></span><span>" + (ok ? "›" : "鎖") + "</span></button>"; }).join("");
}
function openEvent(id) { const e = EVENTS[id]; if (!e) return toast("這個地點目前沒有事件"); q("#event-eyebrow").textContent = e.eyebrow; q("#event-title").textContent = e.title; q("#event-description").textContent = e.description; q("#event-choices").innerHTML = e.choices.map((c) => "<button class=\"choice-button\" data-action=\"choice\" data-event=\"" + id + "\" data-choice=\"" + c.id + "\"><strong>" + c.label + "</strong><span>" + c.note + "</span></button>").join(""); q(".event-sheet").classList.add("open"); q(".event-sheet").setAttribute("aria-hidden","false"); }function choice(id, cid) { const event = EVENTS[id]; const c = event && event.choices.find((x) => x.id === cid); if (!c) return; const w = state.world; const e = c.effect || {}; w.completedEvents = w.completedEvents || []; w.npcs = w.npcs || {}; w.shops = w.shops || {}; w.commissions = w.commissions || []; w.flags = w.flags || []; w.threat = clamp(w.threat + (e.threat || 0),0,99); Object.keys(e.prosperity || {}).forEach((k) => w.settlements[k] = clamp((w.settlements[k] || 0) + e.prosperity[k],0,100)); Object.keys(e.faction || {}).forEach((k) => w.factions[k] = clamp((w.factions[k] || 0) + e.faction[k],-99,99)); if (e.unlock && w.unlocked.indexOf(e.unlock) < 0) w.unlocked.push(e.unlock); if (e.npc) { const old = w.npcs[e.npc.id] || {}; w.npcs[e.npc.id] = { name: e.npc.name, trust: clamp((old.trust || 0) + e.npc.trust,0,99), note: e.npc.note }; } if (e.commission && !w.commissions.some((x) => x.id === e.commission.id)) w.commissions.push({ ...e.commission, status: "available", source: id }); if (e.shop) { const stock = w.shops[e.shop.location] || []; const item = stock.find((x) => x.name === e.shop.item); if (item) item.stock += e.shop.stock; else stock.push({ name: e.shop.item, stock: e.shop.stock, source: id }); w.shops[e.shop.location] = stock; } if (e.flag && w.flags.indexOf(e.flag) < 0) w.flags.push(e.flag); if (w.completedEvents.indexOf(id) < 0) w.completedEvents.push(id); w.lastResult = c.result; state.choices++; q(".event-sheet").classList.remove("open"); render(); save(true); toast(c.result); }
function advance() { const w = state.world; w.day++; w.turns++; w.threat = clamp(w.threat + (state.role === "hermit" ? 2 : 3),0,99); w.season = w.day >= 8 ? "盛夏" : "春潮"; w.settlements["wind-spring"] = clamp(w.settlements["wind-spring"] + (w.threat > 45 ? -1 : 1),0,100); if (!state.role || state.role !== "hero") if (w.turns >= 2 && !w.npcHero) w.npcHero = NPC_HEROES[(w.day + w.turns) % NPC_HEROES.length]; if (w.unlocked.indexOf("sand-ruins") >= 0 && w.day >= 6) w.boss = true; render(); save(); toast(w.npcHero ? w.npcHero + " 已承接天命" : "世界推進至第 " + w.day + " 日"); }
function load() { try { const raw = JSON.parse(localStorage.getItem(SAVE_KEY) || localStorage.getItem("dalu-travel-log-save-v2") || "null"); if (!raw) return; const old = raw.state || raw; state.role = old.role || null; state.choices = old.choices || 0; state.screen = old.screen || "journal"; state.world = Object.assign(initialWorld(), old.world || {}); } catch (e) { localStorage.removeItem(SAVE_KEY); } }
document.addEventListener("click", (ev) => { const n = ev.target.closest("[data-nav]"); if (n) { state.screen = n.dataset.nav; document.querySelectorAll("[data-screen]").forEach((x) => x.classList.toggle("active", x.dataset.screen === state.screen)); document.querySelectorAll("[data-nav]").forEach((x) => x.classList.toggle("active", x.dataset.nav === state.screen)); return; } const a = ev.target.closest("[data-action]"); if (!a) return; if (a.dataset.action === "role") { state.role = a.dataset.role; if (state.role === "hero") state.world.npcHero = null; render(); save(); return; } if (a.dataset.action === "save") return save(); if (a.dataset.action === "advance-world") return advance(); if (a.dataset.action === "open-event") return openEvent(a.dataset.event || "bell"); if (a.dataset.action === "event") return openEvent(a.dataset.event); if (a.dataset.action === "choice") return choice(a.dataset.event,a.dataset.choice); if (a.dataset.action === "close") { q(".event-sheet").classList.remove("open"); return; } if (a.dataset.action === "location") { if (state.world.unlocked.indexOf(a.dataset.location) < 0) return toast("這個地點尚未解鎖"); state.world.activeLocation = a.dataset.location; render(); save(true); toast("目的地已切換：" + LOCATIONS[a.dataset.location].name); } });
document.querySelectorAll("[data-role]").forEach((n) => n.dataset.action = "role");
inject(); load(); render();
if ("serviceWorker" in navigator) navigator.serviceWorker.register("./service-worker.js?v=0.4.4").catch(() => {});
