(() => {
  const COMBAT_KEY = "dalu-combat-v1";
  const SKILLS = {
    slash: { name: "劍氣斬", kind: "attack", shape: "同一列", power: 24, copy: "斬擊目標所在的敵方列。" },
    flare: { name: "爆裂火球", kind: "attack", shape: "十字範圍", power: 18, copy: "以目標為中心波及相鄰敵人。" },
    mend: { name: "治療波", kind: "heal", shape: "亂數 2 名", power: 22, copy: "治療兩名受傷的我方單位。" },
    guard: { name: "盾牆", kind: "guard", shape: "我方前排", power: 12, copy: "前排獲得援護護盾至下回合。" }
  };
  const fresh = () => ({ round: 1, pending: null, winner: null, log: ["鐘影守衛封鎖了北坡，選擇洛恩的第一個行動。"], party: [
    { id: "loen", name: "洛恩", role: "流浪劍士", row: "front", hp: 120, max: 120, speed: 82, guard: 0, avatar: "洛", cls: "ally-a" },
    { id: "yida", name: "伊妲", role: "星紋術士", row: "back", hp: 86, max: 86, speed: 68, guard: 0, avatar: "伊", cls: "ally-b" },
    { id: "tide", name: "潮羽靈", role: "召喚獸", row: "back", hp: 58, max: 58, speed: 74, guard: 0, avatar: "潮", cls: "ally-c" }
  ], enemies: [
    { id: "hound-a", name: "鹽沼獵犬", role: "野獸", row: "front", hp: 54, max: 54, speed: 76, avatar: "犬", cls: "enemy-beast" },
    { id: "warden", name: "鐘影守衛", role: "Boss・構裝體", row: "boss", hp: 112, max: 112, speed: 61, avatar: "鐘", cls: "enemy-boss" },
    { id: "hound-b", name: "鹽沼獵犬", role: "野獸", row: "front", hp: 54, max: 54, speed: 72, avatar: "犬", cls: "enemy-beast" }
  ] });
  let battle = null;
  const all = () => [...(battle?.party || []), ...(battle?.enemies || [])];
  const living = side => (battle?.[side] || []).filter(unit => unit.hp > 0);
  const unit = id => all().find(item => item.id === id);
  const log = message => { battle.log = [message, ...(battle.log || [])].slice(0, 5); };
  const save = () => localStorage.setItem(COMBAT_KEY, JSON.stringify(battle));
  const load = () => { try { battle = JSON.parse(localStorage.getItem(COMBAT_KEY) || "null") || fresh(); } catch { battle = fresh(); } };
  const damage = (target, amount) => { const shield = Number(target.guard || 0); target.guard = Math.max(0, shield - amount); const dealt = Math.max(0, amount - shield); target.hp = Math.max(0, target.hp - dealt); return dealt; };
  const heal = (target, amount) => { target.hp = Math.min(target.max, target.hp + amount); };
  const outcome = () => !living("enemies").length ? "victory" : !living("party").length ? "defeat" : null;
  const enemyTurn = () => { const actor = living("enemies").sort((a, b) => b.speed - a.speed)[0]; const targets = living("party").sort((a, b) => (a.row === "front" ? -1 : 1) - (b.row === "front" ? -1 : 1)); if (!actor || !targets[0]) return; const target = targets[0]; const dealt = damage(target, actor.id === "warden" ? 18 : 11); log(actor.name + "攻擊" + target.name + "，造成 " + dealt + " 點傷害。"); };
  const finish = () => { battle.pending = null; battle.winner = outcome(); if (battle.winner) { log(battle.winner === "victory" ? "鐘影守衛崩解，戰鬥勝利。" : "全員倒下，可重新挑戰這場遭遇戰。"); save(); render(); return; } enemyTurn(); battle.winner = outcome(); battle.round += 1; if (!battle.winner) log("第 " + battle.round + " 回合開始，輪到洛恩。"); save(); render(); };
  const act = (skillId, targetId) => { if (!battle || battle.winner) return; const skill = SKILLS[skillId]; if (!skill) return; if (skill.kind === "attack" && !targetId) { battle.pending = skillId; log(skill.name + "已準備，請選擇敵方目標。"); render(); return; } if (skill.kind === "attack") { const target = unit(targetId); if (!target || target.hp <= 0 || !battle.enemies.includes(target)) return; const targets = skill.shape === "同一列" ? living("enemies").filter(item => item.row === target.row) : living("enemies").filter(item => item.id === target.id || (target.row === "front" && item.row === "front")); targets.forEach(item => damage(item, skill.power)); log("洛恩使用" + skill.name + "，" + targets.map(item => item.name).join("、") + "受到傷害。"); } else if (skill.kind === "heal") { living("party").sort((a, b) => a.hp / a.max - b.hp / b.max).slice(0, 2).forEach(item => heal(item, skill.power)); log("伊妲引導治療波，受傷的我方單位恢復生命。"); } else { living("party").filter(item => item.row === "front").forEach(item => { item.guard = skill.power; }); log("潮羽靈展開盾牆，前排獲得 " + skill.power + " 點援護。"); } finish(); };
  const style = document.createElement("style"); style.textContent = '.bottom-nav{grid-template-columns:repeat(5,1fr)}.battle-launch{width:100%;display:flex;align-items:center;gap:12px;margin-top:12px;padding:15px 16px;border:1px solid rgba(16,44,54,.13);border-radius:19px;background:linear-gradient(120deg,#f0d6a8,#fff5df);color:var(--ink);text-align:left}.battle-launch-icon{width:35px;height:35px;display:grid;place-items:center;border-radius:12px;color:#fff;background:var(--ink);font-size:18px}.battle-launch strong,.battle-launch small{display:block}.battle-launch strong{font-size:14px}.battle-launch small{margin-top:3px;color:var(--ink-soft);font-size:11px}.battle-launch b{margin-left:auto;font-size:23px;color:var(--teal-dark)}.battle-heading{display:flex;align-items:end;justify-content:space-between;gap:12px;padding:12px 3px 8px}.battle-heading h2{margin:0;font-size:28px}.battle-status{display:flex;justify-content:space-between;margin:5px 0 10px;padding:12px 14px;border-radius:14px;color:#fff;background:var(--ink);font-size:12px;font-weight:800}.combat-timeline{display:flex;gap:7px;overflow-x:auto;padding:4px 1px 12px}.combat-timeline span{min-width:48px;display:grid;justify-items:center;gap:3px;color:var(--ink-soft);font-size:9px}.combat-timeline b{width:31px;height:31px;display:grid;place-items:center;border-radius:11px;background:#e7eeea;color:var(--teal-dark)}.combat-timeline .active b{outline:2px solid var(--gold);background:#f3e6ce}.combat-zone{display:grid;gap:10px}.combat-side{padding:13px;border-radius:20px;background:rgba(255,253,248,.85);border:1px solid rgba(16,44,54,.1)}.combat-enemy{background:linear-gradient(145deg,#fff8f0,#f4e9da)}.combat-party{background:linear-gradient(145deg,#f5fbf8,#e8f1ee)}.combat-side-title{display:flex;justify-content:space-between;gap:8px;margin-bottom:9px;font-size:12px;font-weight:800}.combat-side-title small{color:var(--ink-soft);font-size:9px;font-weight:500}.combat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.combat-unit{min-width:0;display:flex;align-items:center;gap:7px;padding:9px 7px;border:1px solid rgba(16,44,54,.1);borde
  const build = () => { const main = document.querySelector('#app-main'); if (!main || document.querySelector('[data-screen="battle"]')) return; const launch = document.createElement('button'); launch.className = 'battle-launch'; launch.dataset.action = 'combat-launch'; launch.innerHTML = '<span class="battle-launch-icon">⚔</span><span><strong>進入鐘丘遭遇戰</strong><small>回合時間軸・前後排・技能目標形狀測試</small></span><b>›</b>'; const card = main.querySelector('.world-card'); if (card) card.insertAdjacentElement('afterend', launch); const nav = document.querySelector('.bottom-nav'); const party = nav?.querySelector('[data-nav="party"]'); if (nav && party && !nav.querySelector('[data-nav="battle"]')) { const item = document.createElement('button'); item.className = 'nav-item'; item.dataset.nav = 'battle'; item.innerHTML = '<span>⚔</span><small>戰鬥</small>'; nav.insertBefore(item, party); } const screen = document.createElement('section'); screen.className = 'screen'; screen.dataset.screen = 'battle'; screen.setAttribute('aria-labelledby','combat-title'); screen.innerHTML = '<div class="battle-heading"><div><p class="eyebrow">鐘丘遭遇戰・回合制原型</p><h2 id="combat-title">鹽脊下的鐘影</h2></div><span class="tag" id="combat-round">第 1 回合</span></div><div class="battle-status"><span id="combat-turn">選擇行動</span><span>行動點 1</span></div><div class="combat-timeline" id="combat-timeline"></div><div class="combat-zone"><div class="combat-side combat-enemy"><div class="combat-side-title"><span>敵方・鐘丘守衛</span><small>Boss 置中／前後排判定</small></div><div class="combat-grid" id="combat-enemies"></div></div><div class="combat-vs">VS</div><div class="combat-side combat-party"><div class="combat-side-title"><span>我方・潮汐雙列</span><small>近戰前排／遠程後排</small></div><div class="combat-grid" id="combat-party"></div></div></div><div class="combat-log" id="combat-log" aria-live="polite"></div><div class="skill-panel"><div class="section-heading compact"><div><p class="eyebrow">技能選擇</p><h3>本回合行動</h3></div><span class="tag" id="combat-hint">先選技能</span></div><div class="combat-skills" id="combat-skills"></div></div><button class="outline-button combat-back" data-action="combat-back">返回旅誌</button>'; main.appendChild(screen); };
  const render = () => { if (!battle || !document.querySelector('#combat-enemies')) return; const order = [...living('party'), ...living('enemies')].sort((a,b) => b.speed-a.speed); document.querySelector('#combat-round').textContent = battle.winner === 'victory' ? '戰鬥勝利' : battle.winner === 'defeat' ? '戰鬥失敗' : '第 ' + battle.round + ' 回合'; document.querySelector('#combat-turn').textContent = battle.winner ? (battle.winner === 'victory' ? '鐘影守衛已被擊破' : '全員倒下，可重新挑戰') : '洛恩的行動'; document.querySelector('#combat-timeline').innerHTML = order.map(item => '<span class="' + (item.id === 'loen' ? 'active' : '') + '"><b>' + item.avatar + '</b><small>' + item.name + '</small></span>').join(''); const card = (item, enemy) => { const ratio = Math.round(item.hp/item.max*100); const canTarget = enemy && battle.pending && item.hp > 0 && !battle.winner; return '<button class="combat-unit ' + item.cls + ' ' + (item.row === 'boss' ? 'boss' : '') + ' ' + (item.hp <= 0 ? 'fallen' : '') + ' ' + (canTarget ? 'targetable' : '') + '" data-combat-target="' + item.id + '" ' + (enemy && item.hp <= 0 ? 'disabled' : '') + '><span class="unit-avatar">' + item.avatar + '</span><span class="unit-copy"><strong>' + item.name + '</strong><small>' + item.role + '・' + (item.row === 'front' ? '前排' : item.row === 'back' ? '後排' : 'Boss 中央') + '</small><span class="hp-bar"><i style="width:' + ratio + '%"></i></span><small>生命 ' + item.hp + '/' + item.max + (item.guard ? '・援護 ' + item.guard : '') + '</small></span></button>'; }; document.querySelector('#combat-enemies').innerHTML = battle.enemies.map(item => card(item,true)).join(''); document.querySelector('#combat-party').innerHTML = battle.party.map(item => card(item,false)).join(''); document.querySelector('#combat-log').innerHTML = battle.log.map(line => '<p>' + line + '</p>').join(''); document.querySelector('#combat-hint').textContent = battle.pending ? SKILLS[battle.pending].name + '：選擇目標' : battle.winner ? '' : '先選技能'; document.querySelector('#combat-skills').innerHTML = Object.entries(SKILLS).map(([id,skill]) => '<button class="combat-skill ' + (battle.pending === id ? 'selected' : '') + '" data-combat-skill="' + id + '" ' + (battle.winner ? 'disabled' : '') + '><strong>' + skill.name + '</strong><span>' + skill.shape + '・' + skill.copy + '</span></button>').join('') + (battle.winner ? '<button class="combat-skill" data-combat-reset="true"><strong>重新挑戰</strong><span>重設本場遭遇戰</span></button>' : ''); };
  const enter = reset => { if (reset || !battle) { battle = fresh(); save(); } build(); document.querySelectorAll('[data-screen]').forEach(node => node.classList.toggle('active', node.dataset.screen === 'battle')); document.querySelectorAll('[data-nav]').forEach(node => node.classList.toggle('active', node.dataset.nav === 'battle')); window.scrollTo({top:0,behavior:'smooth'}); render(); };
  document.addEventListener('click', event => { const launch = event.target.closest('[data-action="combat-launch"]'); if (launch) { enter(true); return; } const nav = event.target.closest('[data-nav="battle"]'); if (nav) { load(); build(); document.querySelectorAll('[data-screen]').forEach(node => node.classList.toggle('active', node.dataset.screen === 'battle')); render(); return; } const skill = event.target.closest('[data-combat-skill]'); if (skill) { act(skill.dataset.combatSkill); return; } const target = event.target.closest('[data-combat-target]'); if (target && battle?.pending) { act(battle.pending, target.dataset.combatTarget); return; } if (event.target.closest('[data-combat-reset]')) { enter(true); return; } if (event.target.closest('[data-action="combat-back"]')) { document.querySelectorAll('[data-screen]').forEach(node => node.classList.toggle('active', node.dataset.screen === 'journal')); document.querySelectorAll('[data-nav]').forEach(node => node.classList.toggle('active', node.dataset.nav === 'journal')); return; } });
  build(); load();
})();

if ("serviceWorker" in navigator) navigator.serviceWorker.register("./service-worker.js?v=0.4.0").catch(() => {});
