(function () {
  var KEY = "dalu-combat-v1";
  var skills = {
    slash: { name: "劍氣斬", kind: "attack", shape: "同一列", power: 24, copy: "斬擊目標所在的敵方列。" },
    flare: { name: "爆裂火球", kind: "attack", shape: "十字範圍", power: 18, copy: "以目標為中心波及相鄰敵人。" },
    mend: { name: "治療波", kind: "heal", shape: "亂數 2 名", power: 22, copy: "治療兩名受傷的我方單位。" },
    guard: { name: "盾牆", kind: "guard", shape: "我方前排", power: 12, copy: "前排獲得援護護盾。" }
  };
  var battle = null;
  function fresh() { return { round: 1, pending: "", winner: "", log: ["鐘影守衛封鎖了北坡，選擇洛恩的第一個行動。"], party: [
    { id: "loen", name: "洛恩", role: "流浪劍士", row: "front", hp: 120, max: 120, speed: 82, avatar: "洛", cls: "ally-a", guard: 0 },
    { id: "yida", name: "伊妲", role: "星紋術士", row: "back", hp: 86, max: 86, speed: 68, avatar: "伊", cls: "ally-b", guard: 0 },
    { id: "tide", name: "潮羽靈", role: "召喚獸", row: "back", hp: 58, max: 58, speed: 74, avatar: "潮", cls: "ally-c", guard: 0 }
  ], enemies: [
    { id: "hound-a", name: "鹽沼獵犬", role: "野獸", row: "front", hp: 54, max: 54, speed: 76, avatar: "犬", cls: "enemy-beast", guard: 0 },
    { id: "warden", name: "鐘影守衛", role: "Boss・構裝體", row: "boss", hp: 112, max: 112, speed: 61, avatar: "鐘", cls: "enemy-boss", guard: 0 },
    { id: "hound-b", name: "鹽沼獵犬", role: "野獸", row: "front", hp: 54, max: 54, speed: 72, avatar: "犬", cls: "enemy-beast", guard: 0 }
  ] }; }
  function save() { window.localStorage.setItem(KEY, JSON.stringify(battle)); }
  function load() { try { battle = JSON.parse(window.localStorage.getItem(KEY) || "null") || fresh(); } catch (error) { battle = fresh(); } }
  function living(side) { return battle[side].filter(function (unit) { return unit.hp > 0; }); }
  function find(id) { return battle.party.concat(battle.enemies).filter(function (unit) { return unit.id === id; })[0]; }
  function writeLog(message) { battle.log.unshift(message); battle.log = battle.log.slice(0, 5); }
  function hit(target, amount) { var shield = target.guard || 0; target.guard = Math.max(0, shield - amount); var damage = Math.max(0, amount - shield); target.hp = Math.max(0, target.hp - damage); return damage; }
  function result() { if (!living("enemies").length) return "victory"; if (!living("party").length) return "defeat"; return ""; }
  function enemyTurn() { var enemies = living("enemies").sort(function (a, b) { return b.speed - a.speed; }); var targets = living("party").sort(function (a, b) { return (a.row === "front" ? 0 : 1) - (b.row === "front" ? 0 : 1); }); if (!enemies[0] || !targets[0]) return; var amount = enemies[0].id === "warden" ? 18 : 11; var dealt = hit(targets[0], amount); writeLog(enemies[0].name + "攻擊" + targets[0].name + "，造成 " + dealt + " 點傷害。"); }
  function finish() { battle.pending = ""; battle.winner = result(); if (!battle.winner) { enemyTurn(); battle.winner = result(); battle.round += 1; if (!battle.winner) writeLog("第 " + battle.round + " 回合開始，輪到洛恩。"); } else { writeLog(battle.winner === "victory" ? "鐘影守衛崩解，戰鬥勝利。" : "全員倒下，可重新挑戰這場遭遇戰。"); } save(); render(); }
  function act(id, targetId) { if (!battle || battle.winner) return; var skill = skills[id]; if (!skill) return; if (skill.kind === "attack" && !targetId) { battle.pending = id; writeLog(skill.name + "已準備，請選擇敵方目標。"); render(); return; } if (skill.kind === "attack") { var target = find(targetId); if (!target || target.hp <= 0 || battle.enemies.indexOf(target) < 0) return; var targets = skill.shape === "同一列" ? living("enemies").filter(function (unit) { return unit.row === target.row; }) : living("enemies").filter(function (unit) { return unit.id === target.id || target.row === "front" && unit.row === "front"; }); targets.forEach(function (unit) { hit(unit, skill.power); }); writeLog("洛恩使用" + skill.name + "，" + targets.map(function (unit) { return unit.name; }).join("、") + "受到傷害。"); } else if (skill.kind === "heal") { living("party").sort(function (a, b) { return a.hp / a.max - b.hp / b.max; }).slice(0, 2).forEach(function (unit) { unit.hp = Math.min(unit.max, unit.hp + skill.power); }); writeLog("伊妲引導治療波，受傷的我方單位恢復生命。"); } else { living("party").filter(function (unit) { return unit.row === "front"; }).forEach(function (unit) { unit.guard = skill.power; }); writeLog("潮羽靈展開盾牆，前排獲得 " + skill.power + " 點援護。"); } finish(); }
  function card(unit, enemy) { var width = Math.round(unit.hp / unit.max * 100); var targetable = enemy && battle.pending && unit.hp > 0 && !battle.winner; return '<button class="combat-unit ' + unit.cls + ' ' + (unit.row === "boss" ? "boss" : "") + ' ' + (unit.hp <= 0 ? "fallen" : "") + ' ' + (targetable ? "targetable" : "") + '" data-combat-target="' + unit.id + '" ' + (enemy && unit.hp <= 0 ? "disabled" : "") + '><span class="unit-avatar">' + unit.avatar + '</span><span class="unit-copy"><strong>' + unit.name + '</strong><small>' + unit.role + "・" + (unit.row === "front" ? "前排" : unit.row === "back" ? "後排" : "Boss 中央") + '</small><span class="hp-bar"><i style="width:' + width + '%"></i></span><small>生命 ' + unit.hp + '/' + unit.max + (unit.guard ? "・援護 " + unit.guard : "") + '</small></span></button>'; }
  function render() { if (!battle || !document.querySelector("#combat-enemies")) return; var order = living("party").concat(living("enemies")).sort(function (a, b) { return b.speed - a.speed; }); document.querySelector("#combat-round").textContent = battle.winner === "victory" ? "戰鬥勝利" : battle.winner === "defeat" ? "戰鬥失敗" : "第 " + battle.round + " 回合"; document.querySelector("#combat-turn").textContent = battle.winner ? (battle.winner === "victory" ? "鐘影守衛已被擊破" : "全員倒下，可重新挑戰") : "洛恩的行動"; document.querySelector("#combat-timeline").innerHTML = order.map(function (unit) { return '<span class="' + (unit.id === "loen" ? "active" : "") + '"><b>' + unit.avatar + '</b><small>' + unit.name + '</small></span>'; }).join(""); document.querySelector("#combat-enemies").innerHTML = battle.enemies.map(function (unit) { return card(unit, true); }).join(""); document.querySelector("#combat-party").innerHTML = battle.party.map(function (unit) { return card(unit, false); }).join(""); document.querySelector("#combat-log").innerHTML = battle.log.map(function (line) { return "<p>" + line + "</p>"; }).join(""); document.querySelector("#combat-hint").textContent = battle.pending ? skills[battle.pending].name + "：選擇目標" : battle.winner ? "" : "先選技能"; document.querySelector("#combat-skills").innerHTML = Object.keys(skills).map(function (id) { var skill = skills[id]; return '<button class="combat-skill ' + (battle.pending === id ? "selected" : "") + '" data-combat-skill="' + id + '" ' + (battle.winner ? "disabled" : "") + '><strong>' + skill.name + '</strong><span>' + skill.shape + "・" + skill.copy + '</span></button>'; }).join("") + (battle.winner ? '<button class="combat-skill" data-combat-reset="true"><strong>重新挑戰</strong><span>重設本場遭遇戰</span></button>' : ""); }
  function build() { var main = document.querySelector("#app-main"); if (!main || document.querySelector("[data-screen=\"battle\"]")) return; var launch = document.createElement("button"); launch.className = "battle-launch"; launch.dataset.action = "combat-launch"; launch.innerHTML = '<span class="battle-launch-icon">⚔</span><span><strong>進入鐘丘遭遇戰</strong><small>回合時間軸・前後排・技能目標形狀測試</small></span><b>›</b>'; var world = main.querySelector(".world-card"); if (world) world.insertAdjacentElement("afterend", launch); var nav = document.querySelector(".bottom-nav"); var party = nav && nav.querySelector("[data-nav=\"party\"]"); if (nav && party && !nav.querySelector("[data-nav=\"battle\"]")) { var navItem = document.createElement("button"); navItem.className = "nav-item"; navItem.dataset.nav = "battle"; navItem.innerHTML = "<span>⚔</span><small>戰鬥</small>"; nav.insertBefore(navItem, party); } var screen = document.createElement("section"); screen.className = "screen"; screen.dataset.screen = "battle"; screen.innerHTML = '<div class="battle-heading"><div><p class="eyebrow">鐘丘遭遇戰・回合制原型</p><h2 id="combat-title">鹽脊下的鐘影</h2></div><span class="tag" id="combat-round">第 1 回合</span></div><div class="battle-status"><span id="combat-turn">選擇行動</span><span>行動點 1</span></div><div class="combat-timeline" id="combat-timeline"></div><div class="combat-zone"><div class="combat-side combat-enemy"><div class="combat-side-title"><span>敵方・鐘丘守衛</span><small>Boss 置中／前後排判定</small></div><div class="combat-grid" id="combat-enemies"></div></div><div class="combat-vs">VS</div><div class="combat-side combat-party"><div class="combat-side-title"><span>我方・潮汐雙列</span><small>近戰前排／遠程後排</small></div><div class="combat-grid" id="combat-party"></div></div></div><div class="combat-log" id="combat-log"></div><div class="skill-panel"><div class="section-heading compact"><div><p class="eyebrow">技能選擇</p><h3>本回合行動</h3></div><span class="tag" id="combat-hint">先選技能</span></div><div class="combat-skills" id="combat-skills"></div></div><button class="outline-button combat-back" data-action="combat-back">返回旅誌</button>'; main.appendChild(screen); }
  function enter(reset) { if (reset || !battle) { battle = fresh(); save(); } build(); document.querySelectorAll("[data-screen]").forEach(function (node) { node.classList.toggle("active", node.dataset.screen === "battle"); }); document.querySelectorAll("[data-nav]").forEach(function (node) { node.classList.toggle("active", node.dataset.nav === "battle"); }); render(); }
  document.addEventListener("click", function (event) { var launch = event.target.closest("[data-action=\"combat-launch\"]"); if (launch) { enter(true); return; } var nav = event.target.closest("[data-nav=\"battle\"]"); if (nav) { load(); build(); document.querySelectorAll("[data-screen]").forEach(function (node) { node.classList.toggle("active", node.dataset.screen === "battle"); }); render(); return; } var skill = event.target.closest("[data-combat-skill]"); if (skill) { act(skill.dataset.combatSkill); return; } var target = event.target.closest("[data-combat-target]"); if (target && battle && battle.pending) { act(battle.pending, target.dataset.combatTarget); return; } if (event.target.closest("[data-combat-reset]")) { enter(true); return; } if (event.target.closest("[data-action=\"combat-back\"]")) { document.querySelectorAll("[data-screen]").forEach(function (node) { node.classList.toggle("active", node.dataset.screen === "journal"); }); document.querySelectorAll("[data-nav]").forEach(function (node) { node.classList.toggle("active", node.dataset.nav === "journal"); }); } });
  build(); load();
  if (window.navigator && window.navigator.serviceWorker) window.navigator.serviceWorker.register("./service-worker.js?v=0.4.4").catch(function () {});
}());
