const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const source = fs.readFileSync(path.join(__dirname, "../app.js"), "utf8");
const eventLines = source.split(String.fromCharCode(10)).filter((line) => line.includes("eyebrow:") && line.includes("title:"));
const events = eventLines.map((line) => ({ id: line.trim().split(":")[0], free: line.includes("自由事件") }));
assert.ok(events.length > 0, "event catalog must include events");
assert.equal(new Set(events.map((event) => event.id)).size, events.length, "event IDs must be unique");
const freeCount = events.filter((event) => event.free).length;
assert.ok(freeCount / events.length >= 0.6, "free event share must be at least 60%; got " + freeCount + "/" + events.length);
const start = source.indexOf("const EVENT_POOLS = {");
const end = source.indexOf("function eventFor", start);
assert.ok(start >= 0 && end > start, "event pools must be declared");
const tokens = source.slice(start, end).split(String.fromCharCode(34)).filter((_, i) => i % 2 === 1);
const places = ["wind-spring", "mist-harbor", "bell-hill", "salt-marsh", "sand-ruins"];
const ids = new Set(events.map((event) => event.id));
for (const id of tokens) assert.ok(places.includes(id) || ids.has(id), "unknown pool id: " + id);
for (const event of events) assert.ok(tokens.includes(event.id), "event missing from location pool: " + event.id);
const { applyOutcome } = require("../event-system.js");
const locations = { "wind-spring": { settlement: "wind-spring", faction: "wind-spring-council" }, "mist-harbor": { settlement: "mist-harbor", faction: "salt-road-guild" }, "sand-ruins": { settlement: "wind-spring", faction: "bell-temple" } };
const initial = { day: 7, turns: 4, threat: 98, activeLocation: "wind-spring", settlements: { "wind-spring": 96 }, factions: { "wind-spring-council": 98 }, unlocked: ["wind-spring"], completedEvents: [], npcs: {}, shops: {}, commissions: [], flags: [] };
const choice = { id: "fixture-choice", result: "結果已寫回世界狀態。", effect: { threat: 5, prosperity: { "wind-spring": 8 }, faction: { "wind-spring-council": 5 }, unlock: "sand-ruins", flag: "fixture-complete", npc: { id: "keeper", name: "鐘守人", trust: 4, note: "安全路線" }, shop: { location: "mist-harbor", item: "潮鹽藥包", stock: 2 }, commission: { id: "follow-up", title: "確認安全路線", location: "sand-ruins" } } };
const result = applyOutcome(initial, "fixture-event", choice, { locations, regionId: "spring-coast", location: "wind-spring" });
assert.equal(result.applied, true);
assert.equal(result.world.threat, 99);
assert.equal(result.world.settlements["wind-spring"], 100);
assert.equal(result.world.factions["wind-spring-council"], 99);
assert.ok(result.world.unlocked.includes("sand-ruins"));
assert.equal(result.world.npcs.keeper.factionId, "wind-spring-council");
assert.equal(result.world.shops["mist-harbor"][0].stock, 2);
assert.equal(result.world.commissions[0].status, "available");
assert.equal(result.world.commissions[0].factionId, "bell-temple");
assert.ok(result.world.flags.includes("fixture-complete"));
assert.equal(result.world.eventHistory[0].choiceId, "fixture-choice");
assert.equal(initial.threat, 98, "outcome application must not mutate the original save");
const replay = applyOutcome(result.world, "fixture-event", choice, { locations, regionId: "spring-coast", location: "wind-spring" });
assert.equal(replay.applied, false, "completed event cannot apply twice");
assert.equal(replay.world.shops["mist-harbor"][0].stock, 2);
process.stdout.write("PASS free event audit: " + freeCount + "/" + events.length + " (" + (100 * freeCount / events.length).toFixed(1) + "%)\nPASS result writeback, provenance, immutability, and duplicate guard\n");
