const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const root = path.resolve(__dirname, "..");
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "dalu-build-"));
const build = () => spawnSync(process.execPath, [path.join(temp, "scripts/prepare-android-web.cjs")], { encoding: "utf8" });
try {
  fs.cpSync(root, temp, { recursive: true, filter: src => ![".git", "node_modules", "www", "android", "outputs"].includes(path.relative(root, src).split(path.sep)[0]) });
  let result = build();
  assert.equal(result.status, 0, result.stderr);
  const previous = fs.readFileSync(path.join(temp, "www/index.html"));
  fs.renameSync(path.join(temp, "styles.css"), path.join(temp, "styles.backup"));
  fs.renameSync(path.join(temp, "battle.js"), path.join(temp, "battle.backup"));
  result = build();
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /styles\.css.*battle\.js/);
  assert.deepEqual(fs.readFileSync(path.join(temp, "www/index.html")), previous);
  console.log("PASS missing sources are listed together and previous bundle survives");
  fs.renameSync(path.join(temp, "styles.backup"), path.join(temp, "styles.css"));
  fs.renameSync(path.join(temp, "battle.backup"), path.join(temp, "battle.js"));
  fs.rmSync(path.join(temp, "assets/art/locations/bell-hill.svg"));
  result = build();
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /bell-hill/);
  assert.deepEqual(fs.readFileSync(path.join(temp, "www/index.html")), previous);
  assert.ok(!fs.readdirSync(temp).some(name => name.startsWith(".web-stage-")));
  console.log("PASS missing offline asset rejects staging without replacing previous bundle");
  fs.copyFileSync(path.join(root, "assets/art/locations/bell-hill.svg"), path.join(temp, "assets/art/locations/bell-hill.svg"));
  const version = JSON.parse(fs.readFileSync(path.join(temp, "version.json")));
  version.version = "0.0.0";
  fs.writeFileSync(path.join(temp, "version.json"), JSON.stringify(version));
  result = build();
  assert.notEqual(result.status, 0);
  assert.deepEqual(fs.readFileSync(path.join(temp, "www/index.html")), previous);
  console.log("PASS mixed versions cannot replace previous bundle");
} finally { fs.rmSync(temp, { recursive: true, force: true }); }
