const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const app=path.join(__dirname,"..","qunlu-app");
const atlas=fs.readFileSync(path.join(app,"assets","art","maps","region-atlas.svg"),"utf8");
const ui=fs.readFileSync(path.join(app,"src","xuanyuan-map-ui.js"),"utf8");
const sw=fs.readFileSync(path.join(app,"sw.js"),"utf8");
const version=JSON.parse(fs.readFileSync(path.join(app,"version.json"),"utf8"));
for(const id of ["region-windspring","region-salt-tide","region-sinking-sand","region-mist-harbor"])assert.match(atlas,new RegExp('<symbol id="'+id+'"'),"scene symbol "+id);
for(const id of ["world","realm","province","local","region-islands","region-steppe","region-forest","region-highland","region-marsh","region-desert","region-city","region-riverland"])assert.match(atlas,new RegExp('id="atlas-detail-'+id.replace("region-","")+'"'),"illustrated terrain detail "+id);
assert.equal((atlas.match(/fill="url\(#atlas-etching\)"/g)||[]).length,16,"each zoom level and scene receives engraved terrain texture");
for(const selector of ["風泉村","鹽潮荒野","沉砂遺跡","霧港村"])assert.ok(ui.includes(selector),"scene selector "+selector);
for(const id of ["region-salt-tide","region-sinking-sand","region-mist-harbor"])assert.ok(ui.includes('"'+id+'"'),"wild/dungeon scene route "+id);
assert.match(ui,/town-illustration/,"town uses painterly scene art");
assert.match(ui,/xu-route-map/,"locations render as interactive road-map pins");
assert.match(ui,/call\("travel",l.id,Number\(route.hours\)\|\|1\)/,"adjacent pins invoke real travel");
for(const asset of ["painterly-forest-v1.webp","painterly-coast-v1.webp","painterly-highland-v1.webp","painterly-desert-v1.webp"])assert.ok(ui.includes(asset),"biome scene selector "+asset);
for(const [pattern,label] of [["(?:region-)?(?:forest|windspring)","forest and windspring"],["(?:region-)?(?:highland|mountain)","highland and mountain"],["(?:region-)?(?:islands|coast|marsh)|salt-tide|mist-harbor","island, coastal, marsh and harbor"],["(?:region-)?desert|sinking-sand","desert and sinking sand"]])assert.ok(new RegExp(pattern).test(ui),"biome routing: "+label);
for(const asset of ["painterly-overworld-v1.webp","painterly-region-v1.webp","painterly-town-v1.webp","painterly-dungeon-v1.webp","painterly-forest-v1.webp","painterly-coast-v1.webp","painterly-highland-v1.webp","painterly-desert-v1.webp"]){assert.ok(ui.includes(asset),"map layer selects "+asset);assert.ok(sw.includes("./assets/art/maps/"+asset),"offline cache includes "+asset);assert.ok(fs.existsSync(path.join(app,"assets","art","maps",asset)),"map asset exists "+asset);}
assert.match(sw,/CACHE_NAME=CACHE_PREFIX\+"v46"/,"map cache revision");
assert.match(sw,/\.\/assets\/art\/maps\/region-atlas\.svg/,"map scene asset is cached");
assert.equal(version.version,"CURRENT-1.102.0");
assert.equal(version.pwa_cache_revision,"v46");
console.log("PASS original regional map scenes, interactive location pins, town illustration, and offline cache");
