const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const app=path.join(__dirname,"..","qunlu-app");
const atlas=fs.readFileSync(path.join(app,"assets","art","maps","region-atlas.svg"),"utf8");
const ui=fs.readFileSync(path.join(app,"src","xuanyuan-map-ui.js"),"utf8");
const sw=fs.readFileSync(path.join(app,"sw.js"),"utf8");
const index=fs.readFileSync(path.join(app,"index.html"),"utf8");
const version=JSON.parse(fs.readFileSync(path.join(app,"version.json"),"utf8"));
const css=fs.readFileSync(path.join(app,"assets","css","app-theme.css"),"utf8");
const home=fs.readFileSync(path.join(app,"src","town-home-ui.js"),"utf8");
for(const id of ["region-windspring","region-salt-tide","region-sinking-sand","region-mist-harbor"])assert.match(atlas,new RegExp('<symbol id="'+id+'"'),"scene symbol "+id);
for(const id of ["world","realm","province","local","region-islands","region-steppe","region-forest","region-highland","region-marsh","region-desert","region-city","region-riverland"])assert.match(atlas,new RegExp('id="atlas-detail-'+id.replace("region-","")+'"'),"illustrated terrain detail "+id);
assert.equal((atlas.match(/fill="url\(#atlas-etching\)"/g)||[]).length,16,"each zoom level and scene receives engraved terrain texture");
for(const selector of ["風泉村","鹽潮荒野","沉砂遺跡","霧港村"])assert.ok(ui.includes(selector),"scene selector "+selector);
for(const id of ["region-salt-tide","region-sinking-sand","region-mist-harbor"])assert.ok(ui.includes('"'+id+'"'),"wild/dungeon scene route "+id);
assert.match(ui,/town-illustration/,"town uses original illustrated town art");
assert.match(home,/<details class="town-home-map" open>/,"home map has an accessible native collapse control");
assert.ok(!home.includes("town-home-shortcuts"),"duplicate profile shortcuts are removed in favor of fixed navigation");
assert.match(ui,/xu-route-map/,"locations render as interactive road-map pins");
assert.match(ui,/call\("travel",l.id,Number\(route.hours\)\|\|1\)/,"adjacent pins invoke real travel");
for(const [pattern,label] of [["(?:region-)?(?:forest|windspring)","forest and windspring"],["(?:region-)?(?:highland|mountain)","highland and mountain"],["(?:region-)?(?:islands|coast|marsh)|salt-tide|mist-harbor","island, coastal, marsh and harbor"],["(?:region-)?desert|sinking-sand","desert and sinking sand"]])assert.ok(new RegExp(pattern).test(ui),"biome routing: "+label);
for(const asset of ["world-map-v1.png","kingdom-map-v1.png","local-map-v1.png","town-map-v1.png"]){assert.ok(ui.includes(asset)||getTownHome().includes(asset),"map layer selects "+asset);assert.ok(sw.includes("./assets/art/maps/"+asset),"offline cache includes "+asset);assert.ok(fs.existsSync(path.join(app,"assets","art","maps",asset)),"map asset exists "+asset);}
function getTownHome(){return fs.readFileSync(path.join(app,"src","town-home-ui.js"),"utf8")}
assert.equal(sw.match(/const CACHE_NAME=CACHE_PREFIX\+"(v\d+)"/)?.[1],version.pwa_cache_revision,"service worker and version metadata cache revision stay in sync");
assert.match(sw,/\.\/assets\/art\/maps\/region-atlas\.svg/,"map scene asset is cached");
assert.match(version.version,/^CURRENT-\d+\.\d+\.\d+$/,"release version format");
assert.ok(index.includes("<title>異界旅人 "+version.version+"</title>"),"page title matches release version");
assert.ok(index.includes('<meta name="app-version" content="'+version.version+'">'),"page metadata matches release version");
assert.match(sw,/facility-buildings\.svg/,"illustrated storefronts are cached");
assert.ok(fs.existsSync(path.join(app,"assets","art","town","facility-buildings.svg")),"facility art file exists");
assert.match(version.version,/^CURRENT-1\.\d+\.\d+$/,"four-map release version follows the shared release version metadata");
assert.match(ui,/key==="realm"\|\|key==="province"\?"kingdom-map-v1\.png"/,"realm and province use kingdom scale art");
assert.match(ui,/call\("travel",l\.id,Number\(route\.hours\)\|\|1\)/,"travel remains connected to existing roads");
assert.match(css,/\.xu-route-map\{[^}]*z-index:7;pointer-events:none\}/,"route overlay sits above town art without blocking empty areas");
assert.match(css,/\.town-map-routes\{[^}]*z-index:7;pointer-events:none/,"route wrapper stacks above building art without blocking facilities");
assert.match(css,/\.xu-route-marker\{[^}]*pointer-events:auto/,"road pins accept clicks");
assert.match(css,/\.town-map-canvas\.map-gesture-stage,\.xu-town-board\.map-gesture-stage\{pointer-events:none\}/,"map stage background passes pointer events through");
assert.match(css,/\.town-map-canvas\.map-gesture-stage>\.town-map-transform,\.xu-town-board\.map-gesture-stage>\.xu-town-map-surface/,"map surfaces remain available for dragging and pin clicks");
const badgeAsset="./assets/art/town/shop-badges-v1.webp";
assert.ok(home.includes("const badgePositions={"),"town facilities use a badge sprite atlas");
assert.match(home,/class="town-map-building-badge"/,"town pins render illustrated shop badges");
assert.ok(!home.includes("const icons="),"legacy Unicode facility icon map is removed");
assert.ok(!home.includes("town-map-building-art"),"shop badges replace the old town facility icon art");
assert.ok(ui.includes('class="xu-facility-badge"')&&!ui.includes("facility-buildings.svg#")&&css.includes(".xu-facility-badge"),"layered town map replaces storefront icons with shop badges");
for(const id of ["guild","general","blacksmith","tavern","inn","church","clinic","tailor","alchemy","enchanter","mageguild"])assert.match(home,new RegExp("[{,]"+id+":"),"badge position exists for "+id);
assert.ok(css.includes("shop-badges-v1.webp"),"town map CSS uses the badge atlas");
assert.ok(css.includes("background-size:400% 300%"),"town map selects the correct atlas cells");
assert.ok(sw.includes(badgeAsset),"shop badge atlas is cached for offline play");
assert.ok(fs.existsSync(path.join(app,badgeAsset.replace("./",""))),"shop badge atlas exists");
assert.equal(version.shop_badge_revision,"FORGED-SHOP-BADGES-1.0","badge art revision is recorded");
console.log("PASS four detailed map layers, interactive location pins, town illustration, and offline cache");
