const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const app = path.join(root, "qunlu-app");
const lock = JSON.parse(fs.readFileSync(path.join(app, "source-lock.json"), "utf8"));
assert.equal(lock.source_repository, "alanyen-git/qunlu-game");
assert.equal(lock.rules.includes("read-only source"), true);
for (const file of ["index.html","manifest.webmanifest","sw.js","assets/css/game.css","assets/css/app-theme.css","assets/art/qunlu-party-portraits.svg","assets/art/battle-sd-portraits.svg","assets/art/maps/willow-town.svg","assets/art/maps/old-forest.svg","assets/art/maps/stone-vault.svg","assets/art/maps/mountain-pass.svg","assets/art/maps/river-valley.svg","src/battle-ui-theme.js","src/mobile-map-ui.js","src/town-home-ui.js","src/game-data.js","src/runtime.js","src/data-patches.js","src/pwa.js"]) {
  assert.ok(fs.existsSync(path.join(app, file)), "missing imported app file: " + file);
}
const html = fs.readFileSync(path.join(app, "index.html"), "utf8");
const version = JSON.parse(fs.readFileSync(path.join(app, "version.json"), "utf8"));
assert.ok(html.includes(version.version), "app title must match the published version");
assert.ok(html.includes("<title>異界旅人 " + version.version + "</title>"), "standalone app title must be 異界旅人");
const packagedVersion = html.match(/<meta name="app-version" content="([^"]+)">/);
assert.ok(packagedVersion, "standalone app must expose its packaged version");
assert.equal(packagedVersion[1], version.version, "packaged version must match version.json");
const runtimeSource = fs.readFileSync(path.join(app, "src/runtime.js"), "utf8");
assert.ok(runtimeSource.includes('meta[name="app-version"]'), "web updater must compare against packaged app version");
const mapSource = fs.readFileSync(path.join(app, "src/xuanyuan-map-ui.js"), "utf8");
const mapTheme = fs.readFileSync(path.join(app, "assets/css/app-theme.css"), "utf8");
assert.ok(mapSource.includes("openMapLocationDetail"), "wild and dungeon map nodes must retain location details");
assert.ok(mapTheme.includes("XUANYUAN-MAP-UI-1.2"), "five-layer map art and exploration layout must be present");
assert.ok(mapSource.includes("function local(id)"), "province map must open the local-area layer");
assert.ok(mapSource.includes("function locationMap(id)"), "wild and dungeon nodes must open their illustrated location layer");
assert.ok(mapSource.includes("window.openSettlementRegionMap=local"), "existing settlement-map entrypoint must route to local-area map");
const manifest = JSON.parse(fs.readFileSync(path.join(app, "manifest.webmanifest"), "utf8"));
assert.equal(manifest.name, "異界旅人");
assert.equal(manifest.short_name, "異界旅人");
assert.ok(html.includes('src/game-data.js'));
assert.ok(html.includes('src/runtime.js'));
assert.ok(html.includes('assets/css/app-theme.css'));
assert.ok(html.includes('src/mobile-map-ui.js'));
assert.ok(html.includes('src/battle-ui-theme.js'));
assert.ok(!html.includes("dalu-game-web"));
assert.ok(fs.statSync(path.join(app, "src/game-data.js")).size > 3000000);
assert.ok(html.includes('src/town-home-ui.js'), "town home module must load");
assert.equal(html.includes('data-nav="adventure"'), false, "legacy adventure-home nav must be gone");
assert.ok(html.includes('data-nav="home"'), "town map is the home nav");
const townHome = fs.readFileSync(path.join(app, "src/town-home-ui.js"), "utf8");
assert.ok(townHome.includes("dataset.locationId"), "town map must expose active location state for scene styling");
assert.ok(townHome.includes("townHomeActions"), "actions must appear inside the town-map page");
assert.ok(townHome.includes("角色資料"), "character shortcuts must appear on the town-map page");
assert.equal(runtimeSource.includes('add("城鎮設施","openFacilities()")'), false, "generic town-facilities action must be removed");
assert.ok(fs.readFileSync(path.join(app, "assets/css/app-theme.css"), "utf8").includes("XUANYUAN-HOME-1.0"));
const sw = fs.readFileSync(path.join(app, "sw.js"), "utf8");
assert.ok(sw.includes('CACHE_NAME=CACHE_PREFIX+"v17"'), "new illustrated scene assets must be deployed with a fresh offline cache");
for (const art of ["willow-town.svg", "old-forest.svg", "stone-vault.svg", "mountain-pass.svg", "river-valley.svg"]) assert.ok(sw.includes(art), "scene artwork must be included in the offline cache");
assert.ok(mapTheme.includes("XUANYUAN-ARTKIT-0.1"), "original scene art styles must be present");
assert.equal(version.scene_art_revision, "ORIGINAL-MAP-SCENES-1.1");
assert.ok(mapSource.includes("mountain-site") && mapSource.includes("river-site"), "wilderness map selects terrain art by location context");
require("./qunlu-apk-update.test.cjs");
console.log("Qunlu-derived mobile app source and immutable source lock are present.");
