const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const { scenes } = require("../region-content.js");
const harbor = scenes["mist-harbor"];
assert.ok(harbor, "Mist Harbor must have a local scene record");
assert.equal(harbor.resident.name, "璃澄");
assert.ok(harbor.resident.role.includes("潮標"));
assert.ok(harbor.description.includes("潮標"));
const asset = path.join(root, harbor.image.replace(/^\.\//, ""));
assert.ok(fs.existsSync(asset), "scene art must exist locally for offline use");
const svg = fs.readFileSync(asset, "utf8");
assert.match(svg, /<title[^>]*>霧港村潮標夜航<\/title>/);
assert.match(svg, /<desc[^>]*>.*燈塔.*<\/desc>/);
assert.doesNotMatch(svg, /(?:href|src)=["']https?:/i, "scene art must not fetch remote resources");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const worker = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");
assert.ok(html.indexOf("region-content.js") < html.indexOf("app.js"), "region catalog must load before rendering");
assert.match(app, /DaluRegionContent[\s\S]*location-scene[\s\S]*location-resident/);
assert.match(app, /harborTidekeeper:[\s\S]*title: "被塗掉的潮標"[\s\S]*id: "tidekeeper-li"[\s\S]*commission: \{ id: "mist-harbor-night-route"/);
const poolDeclaration = app.slice(app.indexOf("const EVENT_POOLS = {"), app.indexOf("function eventFor"));
assert.match(poolDeclaration, /"mist-harbor": \[[^\]]*"harborTidekeeper"/);
assert.ok(worker.includes("./assets/art/locations/mist-harbor.svg"), "offline cache must include local scene art");
const hill = scenes["bell-hill"];
assert.ok(hill, "Bell Hill must have a local scene record");
assert.equal(hill.resident.name, "北坡鐘守人");
assert.ok(hill.resident.role.includes("石座"));
assert.ok(hill.description.includes("鹽線"));
const hillAsset = path.join(root, hill.image.replace(/^\.\//, ""));
assert.ok(fs.existsSync(hillAsset), "Bell Hill scene art must exist locally for offline use");
const hillSvg = fs.readFileSync(hillAsset, "utf8");
assert.match(hillSvg, /<title[^>]*>北坡鐘丘斷鐘石座<\/title>/);
assert.match(hillSvg, /<desc[^>]*>.*短草.*銅鐘石座.*<\/desc>/);
assert.doesNotMatch(hillSvg, /(?:href|src)=["']https?:/i, "scene art must not fetch remote resources");
assert.ok(worker.includes("./assets/art/locations/bell-hill.svg"), "offline cache must include Bell Hill art");
console.log("PASS Mist Harbor and Bell Hill scenes, named residents, accessible local art, and offline wiring");
